language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

script:
  - python3 -m unittest

# before_deploy: "echo 'ready?'"

# TODO: configure user and password,
# follow: https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Your encrypted token"
  on:
    tags: true
    branch: master

# after_deploy: "echo 'deploy complete?'"
